In [13]:
import pandas as pd
import zipfile
from io import StringIO
import requests
from io import BytesIO

df = pd.read_csv("./datasets/bank/bank-additional.csv", sep=';')
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,married,basic.9y,no,yes,no,cellular,may,fri,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
1,39,services,single,high.school,no,no,no,telephone,may,fri,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
2,25,services,married,high.school,no,yes,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.962,5228.1,no
3,38,services,married,basic.9y,no,unknown,unknown,telephone,jun,fri,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4,47,admin.,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,30,admin.,married,basic.6y,no,yes,yes,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,no
4115,39,admin.,married,high.school,no,yes,no,telephone,jul,fri,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.959,5228.1,no
4116,27,student,single,high.school,no,no,no,cellular,may,mon,...,2,999,1,failure,-1.8,92.893,-46.2,1.354,5099.1,no
4117,58,admin.,married,high.school,no,no,no,cellular,aug,fri,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no
4118,34,management,single,high.school,no,yes,no,cellular,nov,wed,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.120,5195.8,no

In [ ]:
from sklearn.model_selection import train_test_split
from flaml import AutoML

# Split the data into features (X) and target (y)
X = df.drop(columns=['y'])
y = df['y']

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize AutoML
automl = AutoML()

# Define settings for AutoML
automl_settings = {
    "time_budget": 30,  # Time budget in seconds
    "max_iter": 30,  # Max number of iterations
    "metric": 'accuracy',  # Evaluation metric
    "task": 'classification',  # Task type
    "log_file_name": "automl.log",  # Log file
}

# Run AutoML
automl.fit(X_train, y_train, **automl_settings)

# Evaluate on the test set
print("Best ML model:", automl.best_estimator)
print("Accuracy on test set:", automl.score(X_test, y_test))

[flaml.automl.logger: 03-25 17:15:30] {1728} INFO - task = classification
[flaml.automl.logger: 03-25 17:15:30] {1739} INFO - Evaluation method: cv
[flaml.automl.logger: 03-25 17:15:30] {1838} INFO - Minimizing error metric: 1-accuracy
[flaml.automl.logger: 03-25 17:15:30] {1955} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'sgd', 'lrl1']
[flaml.automl.logger: 03-25 17:15:30] {2258} INFO - iteration 0, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2393} INFO - Estimated sufficient time budget=16804s. Estimated necessary time budget=389s.
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 1.7s,	estimator lgbm's best error=0.1110,	best estimator lgbm's best error=0.1110
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 1.9s,	estimator lgbm's best error=0.1110,	best estimator lgbm's best error=0.1110
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 2, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 2.1s,	estimator lgbm's best error=0.1009,	best estimator lgbm's best error=0.1009
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 3, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 2.3s,	estimator lgbm's best error=0.0853,	best estimator lgbm's best error=0.0853
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 4, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 2.5s,	estimator lgbm's best error=0.0853,	best estimator lgbm's best error=0.0853
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 5, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 2.6s,	estimator lgbm's best error=0.0853,	best estimator lgbm's best error=0.0853
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 6, current learner lgbm
[flaml.automl.logger: 03-25 17:15:32] {2442} INFO -  at 2.7s,	estimator lgbm's best error=0.0853,	best estimator lgbm's best error=0.0853
[flaml.automl.logger: 03-25 17:15:32] {2258} INFO - iteration 7, current learner lgbm
[flaml.automl.logger: 03-25 17:15:33] {2442} INFO -  at 2.8s,	estimator lgbm's best error=0.0853,	best estimator lgbm's best error=0.0853
[flaml.automl.logger: 03-25 17:15:33] {2258} INFO - iteration 8, current learner lgbm
[flaml.automl.logger: 03-25 17:15:33] {2442} INFO -  at 3.0s,	estimator lgbm's best error=0.0812,	best estimator lgbm's best error=0.0812
[flaml.automl.logger: 03-25 17:15:33] {2258} INFO - iteration 9, current learner lgbm
[flaml.automl.logger: 03-25 17:15:33] {2442} INFO -  at 3.1s,	estimator lgbm's best error=0.0812,	best estimator lgbm's best error=0.0812
[flaml.automl.logger: 03-25 17:15:33] {2685} INFO - retrain lgbm for 0.0s
[flaml.automl.logger: 03-25 17:15:33] {2688} INFO - retrained model: LGBMClassifier(colsample_bytree=np.float64(0.930646190497405),
               learning_rate=np.float64(0.38363923015550033), max_bin=1023,
               min_child_samples=11, n_estimators=21, n_jobs=-1, num_leaves=4,
               reg_alpha=0.0009765625, reg_lambda=np.float64(2.292560666768758),
               verbose=-1)
[flaml.automl.logger: 03-25 17:15:33] {1985} INFO - fit succeeded
[flaml.automl.logger: 03-25 17:15:33] {1986} INFO - Time taken to find the best model: 2.9520537853240967
Best ML model: lgbm
Accuracy on test set: 0.8972491909385113